name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main
      - dev
      - prod

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Set your desired AWS region

      - name: Set up Terraform
        run: |
          terraform init

          if [[ ${{ github.ref_name }} == "dev" ]]; then
            terraform init
            terraform apply -var-file="dev.tfvars" -auto-approve
          elif [[ ${{ github.ref_name }} == "prod" ]]; then
            terraform init
            terraform apply -var-file="prod.tfvars" -auto-approve
          else
            echo "No matching branch found. Exiting."
            exit 1
          fi

